from enum import StrEnum


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DELETION_PENDING = "DELETION_PENDING"
    DISABLED = "DISABLED"


class Role(StrEnum):
    STUDENT = "STUDENT"
    REVIEWER = "REVIEWER"
    ADMIN = "ADMIN"


class StudentStage(StrEnum):
    FOUNDATION = "FOUNDATION"
    STRENGTHEN = "STRENGTHEN"
    TRUE_EXAM = "TRUE_EXAM"
    MOCK_EXAM = "MOCK_EXAM"
    SPRINT = "SPRINT"


class Difficulty(StrEnum):
    BASIC = "BASIC"
    MEDIUM = "MEDIUM"
    COMPREHENSIVE = "COMPREHENSIVE"
    TRUE_EXAM = "TRUE_EXAM"


class SourceType(StrEnum):
    TRUE_EXAM = "TRUE_EXAM"
    TEXTBOOK = "TEXTBOOK"
    HANDOUT = "HANDOUT"
    USER_UPLOAD = "USER_UPLOAD"
    GENERATED = "GENERATED"
    WRONG_QUESTION = "WRONG_QUESTION"
    DEMO = "DEMO"


class QuestionQuality(StrEnum):
    DRAFT = "DRAFT"
    VALIDATING = "VALIDATING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    VALID = "VALID"
    REJECTED = "REJECTED"


class TaskType(StrEnum):
    COURSE_LEARNING = "COURSE_LEARNING"
    HANDOUT_PRACTICE = "HANDOUT_PRACTICE"
    ERROR_REVIEW = "ERROR_REVIEW"
    KNOWLEDGE_SUMMARY = "KNOWLEDGE_SUMMARY"
    CHAPTER_TRUE_EXAM = "CHAPTER_TRUE_EXAM"
    FULL_TRUE_EXAM = "FULL_TRUE_EXAM"
    SPECIALIZED_PRACTICE = "SPECIALIZED_PRACTICE"
    THEORY_REVIEW = "THEORY_REVIEW"
    BASIC_QUESTION = "BASIC_QUESTION"
    MEDIUM_QUESTION = "MEDIUM_QUESTION"
    COMPREHENSIVE_QUESTION = "COMPREHENSIVE_QUESTION"
    TRUE_EXAM_QUESTION = "TRUE_EXAM_QUESTION"
    WRONG_QUESTION_REVIEW = "WRONG_QUESTION_REVIEW"
    MOCK_EXAM = "MOCK_EXAM"


class TaskOrigin(StrEnum):
    SYSTEM = "SYSTEM"
    STUDENT = "STUDENT"
    AGENT = "AGENT"
    LEGACY = "LEGACY"


class ChangeActor(StrEnum):
    SYSTEM = "SYSTEM"
    STUDENT = "STUDENT"
    AGENT = "AGENT"


class KnowledgeLearningStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    LEARNING = "LEARNING"
    STRENGTHENING = "STRENGTHENING"
    STRENGTHENED = "STRENGTHENED"


class ResourceType(StrEnum):
    COURSE = "COURSE"
    HANDOUT = "HANDOUT"
    OTHER = "OTHER"


class ResourceStatus(StrEnum):
    DRAFT = "DRAFT"
    PROCESSING = "PROCESSING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    PUBLISHED = "PUBLISHED"
    REJECTED = "REJECTED"


class ResourceImportStatus(StrEnum):
    QUEUED = "QUEUED"
    PARSING = "PARSING"
    MAPPING = "MAPPING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class TargetSchoolChangeStatus(StrEnum):
    PREVIEW = "PREVIEW"
    APPLIED = "APPLIED"
    EXPIRED = "EXPIRED"


class PlanStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class TaskStatus(StrEnum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    SKIPPED = "SKIPPED"
    SUPERSEDED = "SUPERSEDED"
    SUPERSEDED_LEGACY = "SUPERSEDED_LEGACY"


class AttemptContext(StrEnum):
    PRACTICE = "PRACTICE"
    TRUE_EXAM = "TRUE_EXAM"
    MOCK_EXAM = "MOCK_EXAM"


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    WAITING_FOR_REVIEW = "WAITING_FOR_REVIEW"


class AgentRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    STALLED = "STALLED"


class ProposalType(StrEnum):
    MASTERY_UPDATE = "MASTERY_UPDATE"
    ERROR_PROFILE_UPDATE = "ERROR_PROFILE_UPDATE"
    MINOR_ADJUST = "MINOR_ADJUST"
    MAJOR_REPLAN = "MAJOR_REPLAN"
    STAGE_TRANSITION = "STAGE_TRANSITION"
    MOCK_STRATEGY = "MOCK_STRATEGY"


class ProposalStatus(StrEnum):
    PENDING = "PENDING"
    AUTO_COMMITTED = "AUTO_COMMITTED"
    AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class ExamStatus(StrEnum):
    DRAFT = "DRAFT"
    WAITING_FOR_REVIEW = "WAITING_FOR_REVIEW"
    PUBLISHED = "PUBLISHED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"


class MockExamType(StrEnum):
    SPECIALIZED = "SPECIALIZED"
    FULL = "FULL"


class ErrorType(StrEnum):
    CONCEPT = "CONCEPT"
    FORMULA = "FORMULA"
    MODELING = "MODELING"
    CALCULATION = "CALCULATION"
    PROCEDURE = "PROCEDURE"
    PREREQUISITE = "PREREQUISITE"
    READING = "READING"
    CARELESS = "CARELESS"
    TIME_PRESSURE = "TIME_PRESSURE"
    UNKNOWN = "UNKNOWN"
