"""learning plan resources and progression

Revision ID: 25d9c722ddd6
Revises: 6bfa7d1e29e0
Create Date: 2026-08-27 08:51:50.953031
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


revision: str = '25d9c722ddd6'
down_revision: Union[str, None] = '6bfa7d1e29e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for value in (
        'COURSE_LEARNING',
        'HANDOUT_PRACTICE',
        'ERROR_REVIEW',
        'KNOWLEDGE_SUMMARY',
        'CHAPTER_TRUE_EXAM',
        'FULL_TRUE_EXAM',
        'SPECIALIZED_PRACTICE',
    ):
        op.execute(sa.text(f"ALTER TYPE tasktype ADD VALUE IF NOT EXISTS '{value}'"))
    op.execute(sa.text("ALTER TYPE taskstatus ADD VALUE IF NOT EXISTS 'SUPERSEDED_LEGACY'"))
    op.execute(
        sa.text(
            "CREATE TYPE taskorigin AS ENUM ('SYSTEM', 'STUDENT', 'AGENT', 'LEGACY')"
        )
    )
    op.create_table('learning_resources',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('resource_type', sa.Enum('COURSE', 'HANDOUT', 'OTHER', name='resourcetype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'REVIEW_REQUIRED', 'PUBLISHED', 'REJECTED', name='resourcestatus'), nullable=False),
    sa.Column('school_profile_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_profile_id'], ['school_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_resources_resource_type'), 'learning_resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_learning_resources_school_profile_id'), 'learning_resources', ['school_profile_id'], unique=False)
    op.create_index(op.f('ix_learning_resources_status'), 'learning_resources', ['status'], unique=False)
    op.create_table('chapter_true_exam_sessions',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('school_profile_id', sa.UUID(), nullable=False),
    sa.Column('question_snapshot_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('completed_questions', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['school_profile_id'], ['school_profiles.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'knowledge_id', 'question_snapshot_version', name='uq_chapter_exam_snapshot')
    )
    op.create_index(op.f('ix_chapter_true_exam_sessions_knowledge_id'), 'chapter_true_exam_sessions', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_chapter_true_exam_sessions_school_profile_id'), 'chapter_true_exam_sessions', ['school_profile_id'], unique=False)
    op.create_index(op.f('ix_chapter_true_exam_sessions_student_id'), 'chapter_true_exam_sessions', ['student_id'], unique=False)
    op.create_table('resource_review_decisions',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_review_decisions_resource_id'), 'resource_review_decisions', ['resource_id'], unique=False)
    op.create_table('resource_versions',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_resource_content_hash'),
    sa.UniqueConstraint('resource_id', 'version_number', name='uq_resource_version')
    )
    op.create_index(op.f('ix_resource_versions_resource_id'), 'resource_versions', ['resource_id'], unique=False)
    op.create_table('student_availability_templates',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('available_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('available_minutes BETWEEN 0 AND 1440', name='ck_template_minutes'),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name='ck_availability_template_weekday'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'weekday', name='uq_availability_template_weekday')
    )
    op.create_index(op.f('ix_student_availability_templates_student_id'), 'student_availability_templates', ['student_id'], unique=False)
    op.create_table('student_knowledge_progress',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'LEARNING', 'STRENGTHENING', 'STRENGTHENED', name='knowledgelearningstatus'), nullable=False),
    sa.Column('strengthened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strengthened_by_user', sa.Boolean(), nullable=False),
    sa.Column('true_exam_snapshot_version', sa.String(length=64), nullable=True),
    sa.Column('true_exam_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('specialized_unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'knowledge_id', name='uq_student_learning_progress')
    )
    op.create_index(op.f('ix_student_knowledge_progress_knowledge_id'), 'student_knowledge_progress', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_student_knowledge_progress_student_id'), 'student_knowledge_progress', ['student_id'], unique=False)
    op.create_table('target_school_change_previews',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('from_school_id', sa.UUID(), nullable=True),
    sa.Column('to_school_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PREVIEW', 'APPLIED', 'EXPIRED', name='targetschoolchangestatus'), nullable=False),
    sa.Column('preview', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_school_id'], ['school_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_school_change_previews_student_id'), 'target_school_change_previews', ['student_id'], unique=False)
    op.create_index(op.f('ix_target_school_change_previews_to_school_id'), 'target_school_change_previews', ['to_school_id'], unique=False)
    op.create_table('chapter_true_exam_session_questions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chapter_true_exam_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'question_id')
    )
    op.create_table('resource_import_runs',
    sa.Column('resource_version_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PARSING', 'MAPPING', 'REVIEW_REQUIRED', 'SUCCEEDED', 'FAILED', name='resourceimportstatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resource_version_id'], ['resource_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_version_id', name='uq_resource_import_version')
    )
    op.create_index(op.f('ix_resource_import_runs_requested_by_user_id'), 'resource_import_runs', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_resource_import_runs_resource_version_id'), 'resource_import_runs', ['resource_version_id'], unique=False)
    op.create_index(op.f('ix_resource_import_runs_status'), 'resource_import_runs', ['status'], unique=False)
    op.create_table('resource_sections',
    sa.Column('resource_version_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('section_path', sa.String(length=1024), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('suggested_units', sa.Integer(), nullable=True),
    sa.Column('unit_type', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['resource_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_version_id'], ['resource_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_version_id', 'section_path', name='uq_resource_section_path')
    )
    op.create_index(op.f('ix_resource_sections_resource_version_id'), 'resource_sections', ['resource_version_id'], unique=False)
    op.create_table('resource_chunks',
    sa.Column('resource_version_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('extraction_method', sa.String(length=32), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_version_id'], ['resource_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['resource_sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_version_id', 'sequence', name='uq_resource_chunk_sequence')
    )
    op.create_index(op.f('ix_resource_chunks_resource_version_id'), 'resource_chunks', ['resource_version_id'], unique=False)
    op.create_index(op.f('ix_resource_chunks_section_id'), 'resource_chunks', ['section_id'], unique=False)
    op.create_table('resource_knowledge_mappings',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('reviewer_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['resource_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'knowledge_id', name='uq_resource_knowledge_mapping')
    )
    op.create_index(op.f('ix_resource_knowledge_mappings_knowledge_id'), 'resource_knowledge_mappings', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_resource_knowledge_mappings_section_id'), 'resource_knowledge_mappings', ['section_id'], unique=False)
    op.create_table('plan_task_change_events',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('change_sequence', sa.Integer(), nullable=False),
    sa.Column('actor', sa.Enum('SYSTEM', 'STUDENT', 'AGENT', name='changeactor'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['weekly_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['plan_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'change_sequence', name='uq_plan_change_sequence')
    )
    op.create_index(op.f('ix_plan_task_change_events_plan_id'), 'plan_task_change_events', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_task_change_events_task_id'), 'plan_task_change_events', ['task_id'], unique=False)
    op.add_column('feedback', sa.Column('feedback_version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('feedback', sa.Column('detail', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('feedback', sa.Column('mastery_self_score', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('progress_marker', sa.String(length=512), nullable=True))
    op.add_column('plan_tasks', sa.Column('title', sa.String(length=256), server_default='学习任务', nullable=False))
    op.add_column('plan_tasks', sa.Column('description', sa.Text(), server_default='', nullable=False))
    op.add_column('plan_tasks', sa.Column('resource_section_id', sa.UUID(), nullable=True))
    op.add_column('plan_tasks', sa.Column('suggested_scope', sa.String(length=512), nullable=True))
    op.add_column('plan_tasks', sa.Column('planned_units', sa.Integer(), nullable=True))
    op.add_column('plan_tasks', sa.Column('unit_type', sa.String(length=32), nullable=True))
    op.add_column('plan_tasks', sa.Column('system_suggested_minutes', sa.Integer(), server_default='30', nullable=False))
    op.add_column('plan_tasks', sa.Column('student_estimated_minutes', sa.Integer(), nullable=True))
    op.add_column('plan_tasks', sa.Column('effective_minutes', sa.Integer(), server_default='30', nullable=False))
    op.add_column('plan_tasks', sa.Column('origin', sa.Enum('SYSTEM', 'STUDENT', 'AGENT', 'LEGACY', name='taskorigin'), server_default='SYSTEM', nullable=False))
    op.add_column('plan_tasks', sa.Column('is_personal', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('plan_tasks', sa.Column('has_capacity_warning', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('plan_tasks', sa.Column('modified_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_plan_tasks_resource_section_id'), 'plan_tasks', ['resource_section_id'], unique=False)
    op.create_foreign_key('fk_plan_task_resource_section', 'plan_tasks', 'resource_sections', ['resource_section_id'], ['id'], ondelete='SET NULL')
    op.add_column('weekly_plans', sa.Column('timezone', sa.String(length=64), server_default='Asia/Shanghai', nullable=False))
    op.add_column('weekly_plans', sa.Column('last_rolled_at', sa.DateTime(timezone=True), nullable=True))
    op.execute(
        sa.text(
            """
            UPDATE plan_tasks
            SET status = 'SUPERSEDED',
                origin = 'LEGACY',
                title = CASE
                    WHEN task_type = 'BASIC_QUESTION' THEN '旧版基础训练'
                    WHEN task_type = 'MEDIUM_QUESTION' THEN '旧版进阶训练'
                    WHEN task_type = 'COMPREHENSIVE_QUESTION' THEN '旧版综合训练'
                    ELSE '旧版题目任务'
                END,
                description = '迁移前生成的站内题目型待办，已归档但历史答题与反馈保留。',
                system_suggested_minutes = estimated_max_minutes,
                effective_minutes = estimated_max_minutes
            WHERE status IN ('PENDING', 'IN_PROGRESS')
              AND task_type IN (
                  'BASIC_QUESTION', 'MEDIUM_QUESTION', 'COMPREHENSIVE_QUESTION',
                  'TRUE_EXAM_QUESTION', 'WRONG_QUESTION_REVIEW'
              )
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_plans', 'last_rolled_at')
    op.drop_column('weekly_plans', 'timezone')
    op.drop_constraint('fk_plan_task_resource_section', 'plan_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_plan_tasks_resource_section_id'), table_name='plan_tasks')
    op.drop_column('plan_tasks', 'modified_reason')
    op.drop_column('plan_tasks', 'has_capacity_warning')
    op.drop_column('plan_tasks', 'is_personal')
    op.drop_column('plan_tasks', 'origin')
    op.drop_column('plan_tasks', 'effective_minutes')
    op.drop_column('plan_tasks', 'student_estimated_minutes')
    op.drop_column('plan_tasks', 'system_suggested_minutes')
    op.drop_column('plan_tasks', 'unit_type')
    op.drop_column('plan_tasks', 'planned_units')
    op.drop_column('plan_tasks', 'suggested_scope')
    op.drop_column('plan_tasks', 'resource_section_id')
    op.drop_column('plan_tasks', 'description')
    op.drop_column('plan_tasks', 'title')
    op.drop_column('feedback', 'progress_marker')
    op.drop_column('feedback', 'mastery_self_score')
    op.drop_column('feedback', 'detail')
    op.drop_column('feedback', 'feedback_version')
    op.drop_index(op.f('ix_plan_task_change_events_task_id'), table_name='plan_task_change_events')
    op.drop_index(op.f('ix_plan_task_change_events_plan_id'), table_name='plan_task_change_events')
    op.drop_table('plan_task_change_events')
    op.drop_index(op.f('ix_resource_knowledge_mappings_section_id'), table_name='resource_knowledge_mappings')
    op.drop_index(op.f('ix_resource_knowledge_mappings_knowledge_id'), table_name='resource_knowledge_mappings')
    op.drop_table('resource_knowledge_mappings')
    op.drop_index(op.f('ix_resource_chunks_section_id'), table_name='resource_chunks')
    op.drop_index(op.f('ix_resource_chunks_resource_version_id'), table_name='resource_chunks')
    op.drop_table('resource_chunks')
    op.drop_index(op.f('ix_resource_sections_resource_version_id'), table_name='resource_sections')
    op.drop_table('resource_sections')
    op.drop_index(op.f('ix_resource_import_runs_status'), table_name='resource_import_runs')
    op.drop_index(op.f('ix_resource_import_runs_resource_version_id'), table_name='resource_import_runs')
    op.drop_index(op.f('ix_resource_import_runs_requested_by_user_id'), table_name='resource_import_runs')
    op.drop_table('resource_import_runs')
    op.drop_table('chapter_true_exam_session_questions')
    op.drop_index(op.f('ix_target_school_change_previews_to_school_id'), table_name='target_school_change_previews')
    op.drop_index(op.f('ix_target_school_change_previews_student_id'), table_name='target_school_change_previews')
    op.drop_table('target_school_change_previews')
    op.drop_index(op.f('ix_student_knowledge_progress_student_id'), table_name='student_knowledge_progress')
    op.drop_index(op.f('ix_student_knowledge_progress_knowledge_id'), table_name='student_knowledge_progress')
    op.drop_table('student_knowledge_progress')
    op.drop_index(op.f('ix_student_availability_templates_student_id'), table_name='student_availability_templates')
    op.drop_table('student_availability_templates')
    op.drop_index(op.f('ix_resource_versions_resource_id'), table_name='resource_versions')
    op.drop_table('resource_versions')
    op.drop_index(op.f('ix_resource_review_decisions_resource_id'), table_name='resource_review_decisions')
    op.drop_table('resource_review_decisions')
    op.drop_index(op.f('ix_chapter_true_exam_sessions_student_id'), table_name='chapter_true_exam_sessions')
    op.drop_index(op.f('ix_chapter_true_exam_sessions_school_profile_id'), table_name='chapter_true_exam_sessions')
    op.drop_index(op.f('ix_chapter_true_exam_sessions_knowledge_id'), table_name='chapter_true_exam_sessions')
    op.drop_table('chapter_true_exam_sessions')
    op.drop_index(op.f('ix_learning_resources_status'), table_name='learning_resources')
    op.drop_index(op.f('ix_learning_resources_school_profile_id'), table_name='learning_resources')
    op.drop_index(op.f('ix_learning_resources_resource_type'), table_name='learning_resources')
    op.drop_table('learning_resources')
    for enum_name in (
        'changeactor',
        'knowledgelearningstatus',
        'resourceimportstatus',
        'resourcestatus',
        'resourcetype',
        'targetschoolchangestatus',
        'taskorigin',
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS {enum_name}'))
    # ### end Alembic commands ###
