"""create application tables

Revision ID: 6bfa7d1e29e0
Revises: 0001
Create Date: 2026-08-27 00:39:34.458097
"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa


revision: str = '6bfa7d1e29e0'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_events',
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_version', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=96), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('strategy_versions', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aggregate_type', 'aggregate_id', 'aggregate_version', name='uq_event_version')
    )
    op.create_index('ix_domain_events_outbox', 'domain_events', ['published_at', 'occurred_at'], unique=False)
    op.create_table('knowledge_nodes',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tree_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('material_chunks',
    sa.Column('document_id', sa.String(length=96), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('chapter', sa.String(length=128), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('document_version', sa.String(length=32), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_chunks_document_id'), 'material_chunks', ['document_id'], unique=False)
    op.create_table('school_profiles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('school_name', sa.String(length=128), nullable=False),
    sa.Column('major', sa.String(length=128), nullable=False),
    sa.Column('subject_code', sa.String(length=32), nullable=False),
    sa.Column('subject_name', sa.String(length=128), nullable=False),
    sa.Column('syllabus_version', sa.String(length=32), nullable=False),
    sa.Column('source_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('phone_lookup_hash', sa.String(length=64), nullable=False),
    sa.Column('phone_ciphertext', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DELETION_PENDING', 'DISABLED', name='userstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_lookup_hash'), 'users', ['phone_lookup_hash'], unique=True)
    op.create_table('account_deletions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purge_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_account_deletions_purge_after'), 'account_deletions', ['purge_after'], unique=False)
    op.create_table('background_jobs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'WAITING_FOR_REVIEW', name='jobstatus'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_type', 'idempotency_key', name='uq_background_job_idempotency')
    )
    op.create_index('ix_background_jobs_dispatch', 'background_jobs', ['status', 'available_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_user_id'), 'background_jobs', ['user_id'], unique=False)
    op.create_table('exam_profiles',
    sa.Column('school_profile_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('structure', sa.JSON(), nullable=False),
    sa.Column('difficulty_distribution', sa.JSON(), nullable=False),
    sa.Column('knowledge_distribution', sa.JSON(), nullable=False),
    sa.Column('profile_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_profile_id'], ['school_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_profiles_school_profile_id'), 'exam_profiles', ['school_profile_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('route', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'route', 'idempotency_key', name='uq_idempotency_scope')
    )
    op.create_index(op.f('ix_idempotency_records_expires_at'), 'idempotency_records', ['expires_at'], unique=False)
    op.create_index(op.f('ix_idempotency_records_user_id'), 'idempotency_records', ['user_id'], unique=False)
    op.create_table('knowledge_prerequisites',
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('prerequisite_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('knowledge_id', 'prerequisite_id')
    )
    op.create_table('material_chunk_knowledge',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['material_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', 'knowledge_id')
    )
    op.create_table('questions',
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('source_type', sa.Enum('TRUE_EXAM', 'TEXTBOOK', 'HANDOUT', 'USER_UPLOAD', 'GENERATED', 'WRONG_QUESTION', 'DEMO', name='sourcetype'), nullable=False),
    sa.Column('school_profile_id', sa.UUID(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('question_type', sa.String(length=64), nullable=False),
    sa.Column('difficulty', sa.Enum('BASIC', 'MEDIUM', 'COMPREHENSIVE', 'TRUE_EXAM', name='difficulty'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('quality_status', sa.Enum('DRAFT', 'VALIDATING', 'REVIEW_REQUIRED', 'VALID', 'REJECTED', name='questionquality'), nullable=False),
    sa.Column('content_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('estimated_duration_minutes > 0', name='ck_question_duration_positive'),
    sa.CheckConstraint('score > 0', name='ck_question_score_positive'),
    sa.ForeignKeyConstraint(['school_profile_id'], ['school_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_questions_difficulty'), 'questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_questions_question_type'), 'questions', ['question_type'], unique=False)
    op.create_index('ix_questions_selection', 'questions', ['quality_status', 'difficulty', 'question_type'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_sessions_expires_at'), 'refresh_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    op.create_table('school_knowledge_stats',
    sa.Column('school_profile_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('normalized_weight', sa.Float(), nullable=False),
    sa.Column('years_covered', sa.Integer(), nullable=False),
    sa.Column('last_seen_year', sa.Integer(), nullable=True),
    sa.Column('trend', sa.String(length=32), nullable=False),
    sa.Column('source_refs', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_profile_id'], ['school_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('school_profile_id', 'knowledge_id')
    )
    op.create_table('students',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_school_id', sa.UUID(), nullable=True),
    sa.Column('exam_subject', sa.String(length=128), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('current_stage', sa.Enum('FOUNDATION', 'STRENGTHEN', 'TRUE_EXAM', 'MOCK_EXAM', 'SPRINT', name='studentstage'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_school_id'], ['school_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('true_exams',
    sa.Column('school_profile_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('source_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_profile_id'], ['school_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_profile_id', 'year', name='uq_true_exam_school_year')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'REVIEWER', 'ADMIN', name='role'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role')
    )
    op.create_table('agent_runs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('goal', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'STALLED', name='agentrunstatus'), nullable=False),
    sa.Column('model_version', sa.String(length=96), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('loop_count', sa.Integer(), nullable=False),
    sa.Column('tool_call_count', sa.Integer(), nullable=False),
    sa.Column('termination_reason', sa.String(length=64), nullable=True),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['background_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_agent_runs_student_id'), 'agent_runs', ['student_id'], unique=False)
    op.create_table('efficiency_profiles',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.Enum('THEORY_REVIEW', 'BASIC_QUESTION', 'MEDIUM_QUESTION', 'COMPREHENSIVE_QUESTION', 'TRUE_EXAM_QUESTION', 'WRONG_QUESTION_REVIEW', 'MOCK_EXAM', name='tasktype'), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('recent_samples_seconds', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('p50_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('p75_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('average_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'task_type', 'knowledge_id', name='uq_efficiency_profile', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_efficiency_profiles_student_id'), 'efficiency_profiles', ['student_id'], unique=False)
    op.create_table('error_profiles',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('error_type', sa.Enum('CONCEPT', 'FORMULA', 'MODELING', 'CALCULATION', 'PROCEDURE', 'PREREQUISITE', 'READING', 'CARELESS', 'TIME_PRESSURE', 'UNKNOWN', name='errortype'), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('recent_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_attempt_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'knowledge_id', 'error_type', name='uq_error_profile')
    )
    op.create_index(op.f('ix_error_profiles_student_id'), 'error_profiles', ['student_id'], unique=False)
    op.create_table('mock_exams',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('exam_profile_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('mock_type', sa.Enum('SPECIALIZED', 'FULL', name='mockexamtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'WAITING_FOR_REVIEW', 'PUBLISHED', 'IN_PROGRESS', 'COMPLETED', name='examstatus'), nullable=False),
    sa.Column('target_knowledge_id', sa.UUID(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('strategy_version', sa.String(length=32), nullable=False),
    sa.Column('validation_result', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_profile_id'], ['exam_profiles.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_knowledge_id'], ['knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_exams_student_id'), 'mock_exams', ['student_id'], unique=False)
    op.create_table('question_knowledge',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'knowledge_id')
    )
    op.create_table('student_availability',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('available_date', sa.Date(), nullable=False),
    sa.Column('available_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('available_minutes BETWEEN 0 AND 1440', name='ck_available_minutes'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'available_date', name='uq_availability_student_date')
    )
    op.create_index(op.f('ix_student_availability_student_id'), 'student_availability', ['student_id'], unique=False)
    op.create_table('student_knowledge_states',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recent_accuracy', sa.Float(), nullable=True),
    sa.Column('recent_avg_duration', sa.Float(), nullable=True),
    sa.Column('error_streak', sa.Integer(), nullable=False),
    sa.Column('correct_streak', sa.Integer(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_mastery_confidence'),
    sa.CheckConstraint('mastery_score BETWEEN 0 AND 1', name='ck_mastery_score'),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'knowledge_id', name='uq_student_knowledge')
    )
    op.create_index(op.f('ix_student_knowledge_states_knowledge_id'), 'student_knowledge_states', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_student_knowledge_states_student_id'), 'student_knowledge_states', ['student_id'], unique=False)
    op.create_table('true_exam_attempts',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('true_exam_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['true_exam_id'], ['true_exams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'idempotency_key', name='uq_true_exam_attempt_idempotency')
    )
    op.create_index(op.f('ix_true_exam_attempts_student_id'), 'true_exam_attempts', ['student_id'], unique=False)
    op.create_table('true_exam_profiles',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('school_profile_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('average_score_ratio', sa.Float(), nullable=False),
    sa.Column('average_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['school_profile_id'], ['school_profiles.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'school_profile_id', 'knowledge_id', name='uq_true_exam_profile')
    )
    op.create_index(op.f('ix_true_exam_profiles_student_id'), 'true_exam_profiles', ['student_id'], unique=False)
    op.create_table('true_exam_questions',
    sa.Column('true_exam_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['true_exam_id'], ['true_exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('true_exam_id', 'question_id')
    )
    op.create_table('weekly_plans',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('parent_plan_id', sa.UUID(), nullable=True),
    sa.Column('planner_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUPERSEDED', 'COMPLETED', 'CANCELLED', name='planstatus'), nullable=False),
    sa.Column('generated_reason', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'start_date', 'revision', name='uq_plan_revision')
    )
    op.create_index(op.f('ix_weekly_plans_student_id'), 'weekly_plans', ['student_id'], unique=False)
    op.create_table('agent_steps',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.Column('observation_digest', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=96), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'step_number', name='uq_agent_step_number')
    )
    op.create_index(op.f('ix_agent_steps_run_id'), 'agent_steps', ['run_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'step_number', name='uq_checkpoint_step')
    )
    op.create_index(op.f('ix_checkpoints_run_id'), 'checkpoints', ['run_id'], unique=False)
    op.create_table('generated_question_candidates',
    sa.Column('requested_by_student_id', sa.UUID(), nullable=True),
    sa.Column('mock_exam_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('generator_model', sa.String(length=96), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('generation_seed', sa.String(length=64), nullable=False),
    sa.Column('validation_result', sa.JSON(), nullable=False),
    sa.Column('quality_status', sa.Enum('DRAFT', 'VALIDATING', 'REVIEW_REQUIRED', 'VALID', 'REJECTED', name='questionquality'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mock_exam_id'], ['mock_exams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_exam_attempts',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('mock_exam_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mock_exam_id'], ['mock_exams.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'idempotency_key', name='uq_mock_attempt_idempotency')
    )
    op.create_index(op.f('ix_mock_exam_attempts_student_id'), 'mock_exam_attempts', ['student_id'], unique=False)
    op.create_table('mock_exam_questions',
    sa.Column('mock_exam_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mock_exam_id'], ['mock_exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('mock_exam_id', 'question_id')
    )
    op.create_table('plan_tasks',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('task_date', sa.Date(), nullable=False),
    sa.Column('task_type', sa.Enum('THEORY_REVIEW', 'BASIC_QUESTION', 'MEDIUM_QUESTION', 'COMPREHENSIVE_QUESTION', 'TRUE_EXAM_QUESTION', 'WRONG_QUESTION_REVIEW', 'MOCK_EXAM', name='tasktype'), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('estimated_min_minutes', sa.Integer(), nullable=False),
    sa.Column('estimated_max_minutes', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', 'SUPERSEDED', name='taskstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('estimated_max_minutes >= estimated_min_minutes', name='ck_task_duration'),
    sa.CheckConstraint('estimated_min_minutes >= 0', name='ck_task_min_duration'),
    sa.ForeignKeyConstraint(['plan_id'], ['weekly_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_tasks_plan_id'), 'plan_tasks', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_tasks_task_date'), 'plan_tasks', ['task_date'], unique=False)
    op.create_table('proposals',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('proposal_type', sa.Enum('MASTERY_UPDATE', 'ERROR_PROFILE_UPDATE', 'MINOR_ADJUST', 'MAJOR_REPLAN', 'STAGE_TRANSITION', 'MOCK_STRATEGY', name='proposaltype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AUTO_COMMITTED', 'AWAITING_CONFIRMATION', 'APPROVED', 'REJECTED', 'EXPIRED', name='proposalstatus'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('reason_codes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_refs', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'idempotency_key', name='uq_proposal_idempotency')
    )
    op.create_index(op.f('ix_proposals_run_id'), 'proposals', ['run_id'], unique=False)
    op.create_index(op.f('ix_proposals_student_id'), 'proposals', ['student_id'], unique=False)
    op.create_table('feedback',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('completion_ratio', sa.Float(), nullable=False),
    sa.Column('actual_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('looked_at_solution', sa.Boolean(), nullable=False),
    sa.Column('perceived_difficulty', sa.Integer(), nullable=True),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('completion_ratio BETWEEN 0 AND 1', name='ck_feedback_completion'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['plan_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'idempotency_key', name='uq_feedback_idempotency'),
    sa.UniqueConstraint('student_id', 'task_id', name='uq_feedback_task')
    )
    op.create_index(op.f('ix_feedback_student_id'), 'feedback', ['student_id'], unique=False)
    op.create_table('plan_task_knowledge',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['plan_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'knowledge_id')
    )
    op.create_table('plan_task_questions',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['plan_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'question_id')
    )
    op.create_table('question_attempts',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('plan_task_id', sa.UUID(), nullable=True),
    sa.Column('true_exam_attempt_id', sa.UUID(), nullable=True),
    sa.Column('mock_exam_id', sa.UUID(), nullable=True),
    sa.Column('context', sa.Enum('PRACTICE', 'TRUE_EXAM', 'MOCK_EXAM', name='attemptcontext'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('score_ratio', sa.Float(), nullable=False),
    sa.Column('looked_at_solution', sa.Boolean(), nullable=False),
    sa.Column('self_difficulty', sa.Integer(), nullable=True),
    sa.Column('student_error_note', sa.Text(), nullable=True),
    sa.Column('agent_error_type', sa.Enum('CONCEPT', 'FORMULA', 'MODELING', 'CALCULATION', 'PROCEDURE', 'PREREQUISITE', 'READING', 'CARELESS', 'TIME_PRESSURE', 'UNKNOWN', name='errortype'), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('actual_duration_seconds > 0', name='ck_attempt_duration'),
    sa.CheckConstraint('score_ratio BETWEEN 0 AND 1', name='ck_attempt_score_ratio'),
    sa.ForeignKeyConstraint(['plan_task_id'], ['plan_tasks.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'idempotency_key', name='uq_attempt_idempotency')
    )
    op.create_index(op.f('ix_question_attempts_student_id'), 'question_attempts', ['student_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['generated_question_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_candidate_id'), 'review_decisions', ['candidate_id'], unique=False)
    op.create_table('tool_invocations',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=96), nullable=False),
    sa.Column('tool_version', sa.String(length=32), nullable=False),
    sa.Column('args_digest', sa.String(length=64), nullable=False),
    sa.Column('observation_digest', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['agent_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_invocations_run_id'), 'tool_invocations', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_invocations_run_id'), table_name='tool_invocations')
    op.drop_table('tool_invocations')
    op.drop_index(op.f('ix_review_decisions_candidate_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_question_attempts_student_id'), table_name='question_attempts')
    op.drop_table('question_attempts')
    op.drop_table('plan_task_questions')
    op.drop_table('plan_task_knowledge')
    op.drop_index(op.f('ix_feedback_student_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_proposals_student_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_run_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_plan_tasks_task_date'), table_name='plan_tasks')
    op.drop_index(op.f('ix_plan_tasks_plan_id'), table_name='plan_tasks')
    op.drop_table('plan_tasks')
    op.drop_table('mock_exam_questions')
    op.drop_index(op.f('ix_mock_exam_attempts_student_id'), table_name='mock_exam_attempts')
    op.drop_table('mock_exam_attempts')
    op.drop_table('generated_question_candidates')
    op.drop_index(op.f('ix_checkpoints_run_id'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('ix_agent_steps_run_id'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_weekly_plans_student_id'), table_name='weekly_plans')
    op.drop_table('weekly_plans')
    op.drop_table('true_exam_questions')
    op.drop_index(op.f('ix_true_exam_profiles_student_id'), table_name='true_exam_profiles')
    op.drop_table('true_exam_profiles')
    op.drop_index(op.f('ix_true_exam_attempts_student_id'), table_name='true_exam_attempts')
    op.drop_table('true_exam_attempts')
    op.drop_index(op.f('ix_student_knowledge_states_student_id'), table_name='student_knowledge_states')
    op.drop_index(op.f('ix_student_knowledge_states_knowledge_id'), table_name='student_knowledge_states')
    op.drop_table('student_knowledge_states')
    op.drop_index(op.f('ix_student_availability_student_id'), table_name='student_availability')
    op.drop_table('student_availability')
    op.drop_table('question_knowledge')
    op.drop_index(op.f('ix_mock_exams_student_id'), table_name='mock_exams')
    op.drop_table('mock_exams')
    op.drop_index(op.f('ix_error_profiles_student_id'), table_name='error_profiles')
    op.drop_table('error_profiles')
    op.drop_index(op.f('ix_efficiency_profiles_student_id'), table_name='efficiency_profiles')
    op.drop_table('efficiency_profiles')
    op.drop_index(op.f('ix_agent_runs_student_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('user_roles')
    op.drop_table('true_exams')
    op.drop_table('students')
    op.drop_table('school_knowledge_stats')
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_expires_at'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index('ix_questions_selection', table_name='questions')
    op.drop_index(op.f('ix_questions_question_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('material_chunk_knowledge')
    op.drop_table('knowledge_prerequisites')
    op.drop_index(op.f('ix_idempotency_records_user_id'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_expires_at'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_exam_profiles_school_profile_id'), table_name='exam_profiles')
    op.drop_table('exam_profiles')
    op.drop_index(op.f('ix_background_jobs_user_id'), table_name='background_jobs')
    op.drop_index('ix_background_jobs_dispatch', table_name='background_jobs')
    op.drop_table('background_jobs')
    op.drop_index(op.f('ix_account_deletions_purge_after'), table_name='account_deletions')
    op.drop_table('account_deletions')
    op.drop_index(op.f('ix_users_phone_lookup_hash'), table_name='users')
    op.drop_table('users')
    op.drop_table('school_profiles')
    op.drop_index(op.f('ix_material_chunks_document_id'), table_name='material_chunks')
    op.drop_table('material_chunks')
    op.drop_table('knowledge_nodes')
    op.drop_index('ix_domain_events_outbox', table_name='domain_events')
    op.drop_table('domain_events')
    for enum_name in (
        'attemptcontext',
        'agentrunstatus',
        'difficulty',
        'errortype',
        'examstatus',
        'jobstatus',
        'mockexamtype',
        'planstatus',
        'proposalstatus',
        'proposaltype',
        'questionquality',
        'role',
        'sourcetype',
        'studentstage',
        'taskstatus',
        'tasktype',
        'userstatus',
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS {enum_name}'))
    # ### end Alembic commands ###
