"""chapter session attempt link

Revision ID: ed14e801e0dc
Revises: 25d9c722ddd6
Create Date: 2026-08-27 13:03:49.372396
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed14e801e0dc'
down_revision: Union[str, None] = '25d9c722ddd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_attempts', sa.Column('chapter_true_exam_session_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_question_attempts_chapter_true_exam_session_id'), 'question_attempts', ['chapter_true_exam_session_id'], unique=False)
    op.create_foreign_key('fk_attempt_chapter_session', 'question_attempts', 'chapter_true_exam_sessions', ['chapter_true_exam_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_attempt_chapter_session', 'question_attempts', type_='foreignkey')
    op.drop_index(op.f('ix_question_attempts_chapter_true_exam_session_id'), table_name='question_attempts')
    op.drop_column('question_attempts', 'chapter_true_exam_session_id')
    # ### end Alembic commands ###
